language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install
after_success:
  - if [ $TRAVIS_BRANCH != 'master' ]; then exit 0; fi
  - rm -rf node_modules
  - openssl aes-256-cbc -K $encrypted_8dbf7e943a18_key -iv $encrypted_8dbf7e943a18_iv -in .travis/mourgos_deploy.enc -out .travis/mourgos_deploy -d
  - openssl aes-256-cbc -K $encrypted_b3711dfa409f_key -iv $encrypted_b3711dfa409f_iv -in db/config/production.json.enc -out db/config/production.json -d
  - chmod 600 .travis/mourgos_deploy
  - eval "$(ssh-agent -s)"
  - ssh-add .travis/mourgos_deploy
  - scp -o stricthostkeychecking=no -r ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "source .nvm/nvm.sh; ./deploy_api.sh"
